### ISSUE TITLE
About traning speed: DiT is slower than Unet with same batch size

### ISSUE THREAD

**Issue by SuperiorDtj** [Stability-AI/stable-audio-tools#122]
When the batch size of DiT is 24, the speed of steps completed per second is less than half that of Unet with the same batch size (0.3 step/s vs 0.8 steps/s). Both networks are set with default parameters in json files
 Is this a normal phenomenon?

**Comment by zqevans** [comment]
Yes this is normal, DiTs are stronger but more compute-intensive
