### ISSUE TITLE
does it support standard v-diffusion?

### ISSUE THREAD

**Issue by GenjiB** [Stability-AI/stable-audio-tools#133]
I notice this line: https://github.com/Stability-AI/stable-audio-tools/blob/main/stable_audio_tools/inference/generation.py#L237

Does the pretrained model support this v-diffusion?

**Comment by zqevans** [comment]
It does, even the k-diffusion calls are actually wrapped in a VDenoiser so they're technically running v-diffusion as well. The `sample` function in sampling.py is v-diffusion DDIM.
