### ISSUE TITLE
Finetuning stable-audio-open 1.0 - Model Weights + Configs

### ISSUE THREAD

**Issue by cvillela** [Stability-AI/stable-audio-tools#138]
Hey there!

First of all congratulations on the model, and thanks for open sourcing!

I wanted to finetune the [Stable Audio Open](https://arxiv.org/pdf/2407.14358) model, as oposed to Stable Audio 1 or 2, as the results on the paper look so much more promising than the previous models.

There is already an issue #112 requesting the open weights for the model.

I was also interested in the model_config.json, with the parameters for finetuning. Are those available anywhere? Was anyone able to finetune?

**Comment by Taikakim** [comment]
It's available on the Hugging Face page of Stable Audio Open: 
https://huggingface.co/stabilityai/stable-audio-open-1.0/tree/main

**Comment by cvillela** [comment]
@Taikakim thank you for the reply!

**Comment by nostdub** [comment]
Did anyone of you finetuned it successfully ?
I'm looking to do that myself !
