### ISSUE TITLE
Request: Training config repository

### ISSUE THREAD

**Issue by moiseshorta** [Stability-AI/stable-audio-tools#16]
Hello,

Thanks for open sourcing this framework!

I'm thinking it could be quite valuable to the community to create further .config repositories, with further documentation.

For example, for someone who would like to train a DAC VAE in stereo, it could be valuable to understand how to modify the existing config, especially if it's for beginners. Maybe a discussion would be a great addition, too, to share results and insights.

Best,
M

**Comment by zqevans** [comment]
Yeah I originally had a lot of configs in here, but decided to pare it down to just ones I've gotten to work before. I could add some more. I also created a Discussions section if people want to talk more about it there.
