### ISSUE TITLE
When use s3_wds_example.json to download dataset: No such file or directory: 'aws' 

### ISSUE THREAD

**Issue by Rozenthegoat** [Stability-AI/stable-audio-tools#47]
I use the following command to train the model:

`python ./train.py --dataset-config stable_audio_tools/configs/dataset_configs/s3_wds_example.json --model-config stable_audio_tools/configs/model_configs/txt2audio/stable_audio_1_0.json --name harmonai_train`

Trying to download dataset from AWS S3, but raised the following error:

`FileNotFoundError: [Errno 2] No such file or directory: 'aws'`

Thanks for any help!
![image](https://github.com/Stability-AI/stable-audio-tools/assets/46279088/3b869302-4722-4ef8-80c1-89a0bb280f97)

**Comment by atomrun39** [comment]
@Rozenthegoat Hello, how did you solve this problem? I also encountered it

**Comment by nateraw** [comment]
for those lingering on this like @atomrun39 two first things I'd check would be:

1. do you have `aws` cli installed AND available in PATH? i.e. can you do `aws` in terminal and get output?
2. make sure path to `aws` executable is right when this code runs, else perhaps hardcode it in by checking `which aws` and replacing the path to executable here: https://github.com/Stability-AI/stable-audio-tools/blob/7311840dc3ffb69c9134f83483daa1402ec452e3/stable_audio_tools/data/dataset.py#L276 (this is a hack if you did step 1 wrong, really).

I haven't used aws webdataset loader but I'll check back in when I do if I have similar issue and it isn't solved by the above
