### ISSUE TITLE
dependencies problem

### ISSUE THREAD

**Issue by albedimaria** [Stability-AI/stable-audio-tools#48]
Hi there,

I've been attempting to install the stable-audio-tools package locally by cloning the repository, due to some pip installation dependency issues. However, in both cases, I've encountered a specific problem related to the pedalboard dependency version. The installation process is halted with the following error messages:

ERROR: Could not find a version that satisfies the requirement pedalboard==0.7.4 (from stable-audio-tools) (from versions: 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9)
ERROR: No matching distribution found for pedalboard==0.7.4

It seems that stable-audio-tools requires pedalboard==0.7.4, but only newer versions of pedalboard are available.
I'm keen to hear if there's a workaround or if an update to accommodate newer pedalboard versions is possible.

Thank you in advance

**Comment by jakiestfu** [comment]
I believe you need to be on python `3.8.12` @albedimaria. Just dealing with this issue myself.

**Comment by albedimaria** [comment]
thanks, it actually worked.
