### ISSUE TITLE
missing musicgen 

### ISSUE THREAD

**Issue by wangyang2014** [Stability-AI/stable-audio-tools#57]
Hi dear:
     this is good job. Thank you for your open source work
     The model type includes musicgen, but the model and training files are missing the musicgen module. Can the files be completed?

**Comment by nateraw** [comment]
Can you be a little more specific? I noticed there were some changes here with musicgen recently, but the module still exists, as does the config for it. I haven't tried using it but I may be able to help.

**Comment by wangyang2014** [comment]
> Can you be a little more specific? I noticed there were some changes here with musicgen recently, but the module still exists, as does the config for it. I haven't tried using it but I may be able to help.
thank you for your reply，
I have solved it. When I saw this commit, I learned that the reason why musicgen is not supported is that the author deleted the musicgen part.
https://github.com/Stability-AI/stable-audio-tools/commit/408cb44f7ca54b4b5da7833198d830d85d3a8601

thank you

**Comment by zqevans** [comment]
Yeah, I removed MusicGen support because it wasn't fully fleshed out, didn't have inference code, and didn't make checkpoints that were compatible with the official MusicGen code, so it wasn't terribly useful.
