### ISSUE TITLE
Is it neccesarry that the latent space has approximately unit variance？

### ISSUE THREAD

**Issue by hongwen-sun** [Stability-AI/stable-audio-tools#62]
The scale_factor in the original [latent diffusion paper](https://arxiv.org/abs/2112.10752) ensures that the initial latent space on which the diffusion model is operating has approximately unit variance. 
[https://github.com/huggingface/diffusers/issues/437](https://github.com/huggingface/diffusers/issues/437)

**Comment by BingliangLi** [comment]
Good point! My latent train/data_std is about 0.15 and train/latent_std is around 0.8-0.9, I'm training stable audio 2.0 VAE on a combination of speech, music, and general audio datasets.

**Comment by BingliangLi** [comment]
After training the VAE on a much diverse and larger dataset for 300000+ steps, my train/latent_std is around 1.
