### ISSUE TITLE
If train.py runs with 'strategy=None' it throws a ValueError. Maybe 'auto' should be the default?

### ISSUE THREAD

**Issue by ngwnos** [Stability-AI/stable-audio-tools#7]
Running train.py with a single GPU and no --strategy parameter gives the error:
>```ValueError: You selected an invalid strategy name: `strategy=None`. It must be either a string or an instance of `pytorch_lightning.strategies.Strategy`. Example choices: auto, ddp, ddp_spawn, deepspeed, ... Find a complete list of options in our documentation at https://lightning.ai```

It's the same whether --num-gpus is set to 1 or not set.

Running with `--strategy SingleDeviceStrategy` gives the error:
>```ValueError: You selected an invalid strategy name: `strategy='singledevicestrategy'`. It must be either a string or an instance of `pytorch_lightning.strategies.Strategy`. Example choices: auto, ddp, ddp_spawn, deepspeed, ... Find a complete list of options in our documentation at https://lightning.ai```

Running with `--strategy auto` works.

**Comment by zqevans** [comment]
Fixed in https://github.com/Stability-AI/stable-audio-tools/commit/b210114c8ad7c8cf851aebefc97a1dfe17de9676
