### ISSUE TITLE
A bug in RotaryEmbedding

### ISSUE THREAD

**Issue by yukara-ikemiya** [Stability-AI/stable-audio-tools#75]
@zqevans 
You may have already noticed, but I found a bug in the implementation of RotaryEmbedding.

Bug -> undefined variable 'seq_len'

https://github.com/Stability-AI/stable-audio-tools/blob/9f11a4f59a78bf7ed811b52c3d6cfb652a596d1c/stable_audio_tools/models/transformer.py#L140

**Comment by zqevans** [comment]
Yeah, that comes from a copy of that line in x-transformers, that line is never actually hit with normal RoPE configs so it doesn't end up being an issue, but I should remove that.

**Comment by yukara-ikemiya** [comment]
I got it, understood. Btw, thank you for providing a nice repository again!
