### ISSUE TITLE
Training from scratch on RTX 3090 doable?

### ISSUE THREAD

**Issue by oxysoft** [Stability-AI/stable-audio-tools#8]
Hi, I was wondering if this is a small model that is suitable for personal training, or is this release more intended for academics with huge funding? If the latter, then I assume fine-tuning at least will be doable?

Cheers!

**Comment by Lumoria** [comment]
When the models release, Zach has mentioned that they intend on fine tuning being possible on consumer GPUs. A 3090 should be more than enough for this.

**Comment by oxysoft** [comment]
Nice, hopefully that's that coming soon. LoRAs and ControlNets let's hope too!

**Comment by zqevans** [comment]
3090 will be fine for autoencoder training, we will see what the requirements are for further models once they're released
